[
  {
   "dni_afiliado": 42,
   "nombre_comercio": "nombre_comercio 1",
   "nombre_afiliado": "nombre_afiliado 1",
   "apellido_afiliado": "apellido_afiliado 1",
   "fecha_emision": 1692820537,
   "estado_pagado": false,
   "id_afiliado": 58,
   "id_comercio": 95,
   "id_orden": "1"
  },
  {
   "dni_afiliado": 44,
   "nombre_comercio": "nombre_comercio 2",
   "nombre_afiliado": "nombre_afiliado 2",
   "apellido_afiliado": "apellido_afiliado 2",
   "fecha_emision": 1692820477,
   "estado_pagado": false,
   "id_afiliado": 22,
   "id_comercio": 16,
   "id_orden": "2"
  },
  {
   "dni_afiliado": 86,
   "nombre_comercio": "nombre_comercio 3",
   "nombre_afiliado": "nombre_afiliado 3",
   "apellido_afiliado": "apellido_afiliado 3",
   "fecha_emision": 1692820417,
   "estado_pagado": false,
   "id_afiliado": 15,
   "id_comercio": 35,
   "id_orden": "3"
  },
  {
   "dni_afiliado": 19,
   "nombre_comercio": "nombre_comercio 4",
   "nombre_afiliado": "nombre_afiliado 4",
   "apellido_afiliado": "apellido_afiliado 4",
   "fecha_emision": 1692820357,
   "estado_pagado": false,
   "id_afiliado": 77,
   "id_comercio": 62,
   "id_orden": "4"
  },
  {
   "dni_afiliado": 34,
   "nombre_comercio": "nombre_comercio 5",
   "nombre_afiliado": "nombre_afiliado 5",
   "apellido_afiliado": "apellido_afiliado 5",
   "fecha_emision": 1692820297,
   "estado_pagado": false,
   "id_afiliado": 7,
   "id_comercio": 82,
   "id_orden": "5"
  },
  {
   "dni_afiliado": 99,
   "nombre_comercio": "nombre_comercio 6",
   "nombre_afiliado": "nombre_afiliado 6",
   "apellido_afiliado": "apellido_afiliado 6",
   "fecha_emision": 1692820237,
   "estado_pagado": false,
   "id_afiliado": 55,
   "id_comercio": 88,
   "id_orden": "6"
  },
  {
   "dni_afiliado": 1,
   "nombre_comercio": "nombre_comercio 7",
   "nombre_afiliado": "nombre_afiliado 7",
   "apellido_afiliado": "apellido_afiliado 7",
   "fecha_emision": 1692820177,
   "estado_pagado": false,
   "id_afiliado": 9,
   "id_comercio": 34,
   "id_orden": "7"
  },
  {
   "dni_afiliado": 29,
   "nombre_comercio": "nombre_comercio 8",
   "nombre_afiliado": "nombre_afiliado 8",
   "apellido_afiliado": "apellido_afiliado 8",
   "fecha_emision": 1692820117,
   "estado_pagado": false,
   "id_afiliado": 63,
   "id_comercio": 34,
   "id_orden": "8"
  },
  {
   "dni_afiliado": 36,
   "nombre_comercio": "nombre_comercio 9",
   "nombre_afiliado": "nombre_afiliado 9",
   "apellido_afiliado": "apellido_afiliado 9",
   "fecha_emision": 1692820057,
   "estado_pagado": false,
   "id_afiliado": 79,
   "id_comercio": 80,
   "id_orden": "9"
  },
  {
   "dni_afiliado": 77,
   "nombre_comercio": "nombre_comercio 10",
   "nombre_afiliado": "nombre_afiliado 10",
   "apellido_afiliado": "apellido_afiliado 10",
   "fecha_emision": 1692819997,
   "estado_pagado": false,
   "id_afiliado": 91,
   "id_comercio": 46,
   "id_orden": "10"
  },
  {
   "dni_afiliado": 48,
   "nombre_comercio": "nombre_comercio 11",
   "nombre_afiliado": "nombre_afiliado 11",
   "apellido_afiliado": "apellido_afiliado 11",
   "fecha_emision": 1692819937,
   "estado_pagado": false,
   "id_afiliado": 96,
   "id_comercio": 58,
   "id_orden": "11"
  },
  {
   "dni_afiliado": 27,
   "nombre_comercio": "nombre_comercio 12",
   "nombre_afiliado": "nombre_afiliado 12",
   "apellido_afiliado": "apellido_afiliado 12",
   "fecha_emision": 1692819877,
   "estado_pagado": false,
   "id_afiliado": 48,
   "id_comercio": 23,
   "id_orden": "12"
  },
  {
   "dni_afiliado": 78,
   "nombre_comercio": "nombre_comercio 13",
   "nombre_afiliado": "nombre_afiliado 13",
   "apellido_afiliado": "apellido_afiliado 13",
   "fecha_emision": 1692819817,
   "estado_pagado": false,
   "id_afiliado": 76,
   "id_comercio": 92,
   "id_orden": "13"
  },
  {
   "dni_afiliado": 15,
   "nombre_comercio": "nombre_comercio 14",
   "nombre_afiliado": "nombre_afiliado 14",
   "apellido_afiliado": "apellido_afiliado 14",
   "fecha_emision": 1692819757,
   "estado_pagado": false,
   "id_afiliado": 73,
   "id_comercio": 3,
   "id_orden": "14"
  },
  {
   "dni_afiliado": 30,
   "nombre_comercio": "nombre_comercio 15",
   "nombre_afiliado": "nombre_afiliado 15",
   "apellido_afiliado": "apellido_afiliado 15",
   "fecha_emision": 1692819697,
   "estado_pagado": false,
   "id_afiliado": 94,
   "id_comercio": 47,
   "id_orden": "15"
  },
  {
   "dni_afiliado": 55,
   "nombre_comercio": "nombre_comercio 16",
   "nombre_afiliado": "nombre_afiliado 16",
   "apellido_afiliado": "apellido_afiliado 16",
   "fecha_emision": 1692819637,
   "estado_pagado": false,
   "id_afiliado": 74,
   "id_comercio": 100,
   "id_orden": "16"
  },
  {
   "dni_afiliado": 52,
   "nombre_comercio": "nombre_comercio 17",
   "nombre_afiliado": "nombre_afiliado 17",
   "apellido_afiliado": "apellido_afiliado 17",
   "fecha_emision": 1692819577,
   "estado_pagado": false,
   "id_afiliado": 72,
   "id_comercio": 67,
   "id_orden": "17"
  },
  {
   "dni_afiliado": 17,
   "nombre_comercio": "nombre_comercio 18",
   "nombre_afiliado": "nombre_afiliado 18",
   "apellido_afiliado": "apellido_afiliado 18",
   "fecha_emision": 1692819517,
   "estado_pagado": false,
   "id_afiliado": 54,
   "id_comercio": 95,
   "id_orden": "18"
  },
  {
   "dni_afiliado": 28,
   "nombre_comercio": "nombre_comercio 19",
   "nombre_afiliado": "nombre_afiliado 19",
   "apellido_afiliado": "apellido_afiliado 19",
   "fecha_emision": 1692819457,
   "estado_pagado": false,
   "id_afiliado": 65,
   "id_comercio": 65,
   "id_orden": "19"
  },
  {
   "dni_afiliado": 63,
   "nombre_comercio": "nombre_comercio 20",
   "nombre_afiliado": "nombre_afiliado 20",
   "apellido_afiliado": "apellido_afiliado 20",
   "fecha_emision": 1692819397,
   "estado_pagado": false,
   "id_afiliado": 30,
   "id_comercio": 94,
   "id_orden": "20"
  },
  {
   "dni_afiliado": 0,
   "nombre_comercio": "nombre_comercio 21",
   "nombre_afiliado": "nombre_afiliado 21",
   "apellido_afiliado": "apellido_afiliado 21",
   "fecha_emision": 1692819337,
   "estado_pagado": false,
   "id_afiliado": 91,
   "id_comercio": 21,
   "id_orden": "21"
  },
  {
   "dni_afiliado": 66,
   "nombre_comercio": "nombre_comercio 22",
   "nombre_afiliado": "nombre_afiliado 22",
   "apellido_afiliado": "apellido_afiliado 22",
   "fecha_emision": 1692819277,
   "estado_pagado": false,
   "id_afiliado": 1,
   "id_comercio": 56,
   "id_orden": "22"
  },
  {
   "dni_afiliado": 53,
   "nombre_comercio": "nombre_comercio 23",
   "nombre_afiliado": "nombre_afiliado 23",
   "apellido_afiliado": "apellido_afiliado 23",
   "fecha_emision": 1692819217,
   "estado_pagado": false,
   "id_afiliado": 20,
   "id_comercio": 41,
   "id_orden": "23"
  },
  {
   "dni_afiliado": 40,
   "nombre_comercio": "nombre_comercio 24",
   "nombre_afiliado": "nombre_afiliado 24",
   "apellido_afiliado": "apellido_afiliado 24",
   "fecha_emision": 1692819157,
   "estado_pagado": false,
   "id_afiliado": 15,
   "id_comercio": 100,
   "id_orden": "24"
  },
  {
   "dni_afiliado": 43,
   "nombre_comercio": "nombre_comercio 25",
   "nombre_afiliado": "nombre_afiliado 25",
   "apellido_afiliado": "apellido_afiliado 25",
   "fecha_emision": 1692819097,
   "estado_pagado": false,
   "id_afiliado": 3,
   "id_comercio": 93,
   "id_orden": "25"
  },
  {
   "dni_afiliado": 92,
   "nombre_comercio": "nombre_comercio 26",
   "nombre_afiliado": "nombre_afiliado 26",
   "apellido_afiliado": "apellido_afiliado 26",
   "fecha_emision": 1692819037,
   "estado_pagado": false,
   "id_afiliado": 18,
   "id_comercio": 6,
   "id_orden": "26"
  },
  {
   "dni_afiliado": 7,
   "nombre_comercio": "nombre_comercio 27",
   "nombre_afiliado": "nombre_afiliado 27",
   "apellido_afiliado": "apellido_afiliado 27",
   "fecha_emision": 1692818977,
   "estado_pagado": false,
   "id_afiliado": 22,
   "id_comercio": 62,
   "id_orden": "27"
  },
  {
   "dni_afiliado": 53,
   "nombre_comercio": "nombre_comercio 28",
   "nombre_afiliado": "nombre_afiliado 28",
   "apellido_afiliado": "apellido_afiliado 28",
   "fecha_emision": 1692818917,
   "estado_pagado": false,
   "id_afiliado": 4,
   "id_comercio": 18,
   "id_orden": "28"
  },
  {
   "dni_afiliado": 52,
   "nombre_comercio": "nombre_comercio 29",
   "nombre_afiliado": "nombre_afiliado 29",
   "apellido_afiliado": "apellido_afiliado 29",
   "fecha_emision": 1692818857,
   "estado_pagado": false,
   "id_afiliado": 52,
   "id_comercio": 57,
   "id_orden": "29"
  },
  {
   "dni_afiliado": 85,
   "nombre_comercio": "nombre_comercio 30",
   "nombre_afiliado": "nombre_afiliado 30",
   "apellido_afiliado": "apellido_afiliado 30",
   "fecha_emision": 1692818797,
   "estado_pagado": false,
   "id_afiliado": 42,
   "id_comercio": 46,
   "id_orden": "30"
  },
  {
   "dni_afiliado": 20,
   "nombre_comercio": "nombre_comercio 31",
   "nombre_afiliado": "nombre_afiliado 31",
   "apellido_afiliado": "apellido_afiliado 31",
   "fecha_emision": 1692818737,
   "estado_pagado": false,
   "id_afiliado": 37,
   "id_comercio": 62,
   "id_orden": "31"
  },
  {
   "dni_afiliado": 86,
   "nombre_comercio": "nombre_comercio 32",
   "nombre_afiliado": "nombre_afiliado 32",
   "apellido_afiliado": "apellido_afiliado 32",
   "fecha_emision": 1692818677,
   "estado_pagado": false,
   "id_afiliado": 52,
   "id_comercio": 23,
   "id_orden": "32"
  },
  {
   "dni_afiliado": 46,
   "nombre_comercio": "nombre_comercio 33",
   "nombre_afiliado": "nombre_afiliado 33",
   "apellido_afiliado": "apellido_afiliado 33",
   "fecha_emision": 1692818617,
   "estado_pagado": false,
   "id_afiliado": 25,
   "id_comercio": 98,
   "id_orden": "33"
  },
  {
   "dni_afiliado": 52,
   "nombre_comercio": "nombre_comercio 34",
   "nombre_afiliado": "nombre_afiliado 34",
   "apellido_afiliado": "apellido_afiliado 34",
   "fecha_emision": 1692818557,
   "estado_pagado": false,
   "id_afiliado": 21,
   "id_comercio": 75,
   "id_orden": "34"
  },
  {
   "dni_afiliado": 62,
   "nombre_comercio": "nombre_comercio 35",
   "nombre_afiliado": "nombre_afiliado 35",
   "apellido_afiliado": "apellido_afiliado 35",
   "fecha_emision": 1692818497,
   "estado_pagado": false,
   "id_afiliado": 62,
   "id_comercio": 99,
   "id_orden": "35"
  },
  {
   "dni_afiliado": 0,
   "nombre_comercio": "nombre_comercio 36",
   "nombre_afiliado": "nombre_afiliado 36",
   "apellido_afiliado": "apellido_afiliado 36",
   "fecha_emision": 1692818437,
   "estado_pagado": false,
   "id_afiliado": 98,
   "id_comercio": 45,
   "id_orden": "36"
  },
  {
   "dni_afiliado": 74,
   "nombre_comercio": "nombre_comercio 37",
   "nombre_afiliado": "nombre_afiliado 37",
   "apellido_afiliado": "apellido_afiliado 37",
   "fecha_emision": 1692818377,
   "estado_pagado": false,
   "id_afiliado": 19,
   "id_comercio": 24,
   "id_orden": "37"
  },
  {
   "dni_afiliado": 10,
   "nombre_comercio": "nombre_comercio 38",
   "nombre_afiliado": "nombre_afiliado 38",
   "apellido_afiliado": "apellido_afiliado 38",
   "fecha_emision": 1692818317,
   "estado_pagado": false,
   "id_afiliado": 85,
   "id_comercio": 82,
   "id_orden": "38"
  },
  {
   "dni_afiliado": 6,
   "nombre_comercio": "nombre_comercio 39",
   "nombre_afiliado": "nombre_afiliado 39",
   "apellido_afiliado": "apellido_afiliado 39",
   "fecha_emision": 1692818257,
   "estado_pagado": false,
   "id_afiliado": 5,
   "id_comercio": 89,
   "id_orden": "39"
  },
  {
   "dni_afiliado": 57,
   "nombre_comercio": "nombre_comercio 40",
   "nombre_afiliado": "nombre_afiliado 40",
   "apellido_afiliado": "apellido_afiliado 40",
   "fecha_emision": 1692818197,
   "estado_pagado": false,
   "id_afiliado": 77,
   "id_comercio": 44,
   "id_orden": "40"
  },
  {
   "dni_afiliado": 37,
   "nombre_comercio": "nombre_comercio 41",
   "nombre_afiliado": "nombre_afiliado 41",
   "apellido_afiliado": "apellido_afiliado 41",
   "fecha_emision": 1692818137,
   "estado_pagado": false,
   "id_afiliado": 87,
   "id_comercio": 77,
   "id_orden": "41"
  },
  {
   "dni_afiliado": 91,
   "nombre_comercio": "nombre_comercio 42",
   "nombre_afiliado": "nombre_afiliado 42",
   "apellido_afiliado": "apellido_afiliado 42",
   "fecha_emision": 1692818077,
   "estado_pagado": false,
   "id_afiliado": 65,
   "id_comercio": 27,
   "id_orden": "42"
  },
  {
   "dni_afiliado": 24,
   "nombre_comercio": "nombre_comercio 43",
   "nombre_afiliado": "nombre_afiliado 43",
   "apellido_afiliado": "apellido_afiliado 43",
   "fecha_emision": 1692818017,
   "estado_pagado": false,
   "id_afiliado": 18,
   "id_comercio": 55,
   "id_orden": "43"
  },
  {
   "dni_afiliado": 56,
   "nombre_comercio": "nombre_comercio 44",
   "nombre_afiliado": "nombre_afiliado 44",
   "apellido_afiliado": "apellido_afiliado 44",
   "fecha_emision": 1692817957,
   "estado_pagado": false,
   "id_afiliado": 88,
   "id_comercio": 22,
   "id_orden": "44"
  },
  {
   "dni_afiliado": 35,
   "nombre_comercio": "nombre_comercio 45",
   "nombre_afiliado": "nombre_afiliado 45",
   "apellido_afiliado": "apellido_afiliado 45",
   "fecha_emision": 1692817899,
   "estado_pagado": false,
   "id_afiliado": 88,
   "id_comercio": 76,
   "id_orden": "45"
  },
  {
   "dni_afiliado": 63,
   "nombre_comercio": "nombre_comercio 46",
   "nombre_afiliado": "nombre_afiliado 46",
   "apellido_afiliado": "apellido_afiliado 46",
   "fecha_emision": 1692817839,
   "estado_pagado": false,
   "id_afiliado": 64,
   "id_comercio": 47,
   "id_orden": "46"
  },
  {
   "dni_afiliado": 32,
   "nombre_comercio": "nombre_comercio 47",
   "nombre_afiliado": "nombre_afiliado 47",
   "apellido_afiliado": "apellido_afiliado 47",
   "fecha_emision": 1692817779,
   "estado_pagado": false,
   "id_afiliado": 73,
   "id_comercio": 50,
   "id_orden": "47"
  },
  {
   "dni_afiliado": 68,
   "nombre_comercio": "nombre_comercio 48",
   "nombre_afiliado": "nombre_afiliado 48",
   "apellido_afiliado": "apellido_afiliado 48",
   "fecha_emision": 1692817719,
   "estado_pagado": false,
   "id_afiliado": 31,
   "id_comercio": 54,
   "id_orden": "48"
  },
  {
   "dni_afiliado": 26,
   "nombre_comercio": "nombre_comercio 49",
   "nombre_afiliado": "nombre_afiliado 49",
   "apellido_afiliado": "apellido_afiliado 49",
   "fecha_emision": 1692817659,
   "estado_pagado": false,
   "id_afiliado": 4,
   "id_comercio": 61,
   "id_orden": "49"
  },
  {
   "dni_afiliado": 54,
   "nombre_comercio": "nombre_comercio 50",
   "nombre_afiliado": "nombre_afiliado 50",
   "apellido_afiliado": "apellido_afiliado 50",
   "fecha_emision": 1692817599,
   "estado_pagado": false,
   "id_afiliado": 28,
   "id_comercio": 66,
   "id_orden": "50"
  },
  {
   "dni_afiliado": 66,
   "nombre_comercio": "nombre_comercio 51",
   "nombre_afiliado": "nombre_afiliado 51",
   "apellido_afiliado": "apellido_afiliado 51",
   "fecha_emision": 1692817539,
   "estado_pagado": false,
   "id_afiliado": 85,
   "id_comercio": 22,
   "id_orden": "51"
  },
  {
   "dni_afiliado": 21,
   "nombre_comercio": "nombre_comercio 52",
   "nombre_afiliado": "nombre_afiliado 52",
   "apellido_afiliado": "apellido_afiliado 52",
   "fecha_emision": 1692817479,
   "estado_pagado": false,
   "id_afiliado": 46,
   "id_comercio": 70,
   "id_orden": "52"
  },
  {
   "dni_afiliado": 32,
   "nombre_comercio": "nombre_comercio 53",
   "nombre_afiliado": "nombre_afiliado 53",
   "apellido_afiliado": "apellido_afiliado 53",
   "fecha_emision": 1692817419,
   "estado_pagado": false,
   "id_afiliado": 51,
   "id_comercio": 31,
   "id_orden": "53"
  },
  {
   "dni_afiliado": 24,
   "nombre_comercio": "nombre_comercio 54",
   "nombre_afiliado": "nombre_afiliado 54",
   "apellido_afiliado": "apellido_afiliado 54",
   "fecha_emision": 1692817359,
   "estado_pagado": false,
   "id_afiliado": 17,
   "id_comercio": 71,
   "id_orden": "54"
  },
  {
   "dni_afiliado": 14,
   "nombre_comercio": "nombre_comercio 55",
   "nombre_afiliado": "nombre_afiliado 55",
   "apellido_afiliado": "apellido_afiliado 55",
   "fecha_emision": 1692817299,
   "estado_pagado": false,
   "id_afiliado": 13,
   "id_comercio": 53,
   "id_orden": "55"
  }
 ]